### ISSUE TITLE
make different views for different users

### ISSUE THREAD

**Issue by xlqian** [CanalTP/navitia-playground#120]
current view is a "pro-creation" view, while experienced users prefer a "pro-debug" view, which means with a more compacted view for creation to avoid scrolling 

An idea may be reuse the view with creation on column

**Comment by xlqian** [comment]
@TeXitoi that's a good idea, with this lib(http://webcloud.se/jQuery-Collapse/) it wouldn't be too difficult to do it

**Comment by pbougue** [comment]
With some slow movement (same as issue on MAP/EXT) it can be nice :)
