### ISSUE TITLE
Make the generated URL a link

### ISSUE THREAD

**Issue by pbougue** [CanalTP/navitia-playground#135]
With the different colors, it's a bit difficult to know what is selected in generated URL, so maybe a button would be nice...

**Comment by TeXitoi** [comment]
http://stackoverflow.com/questions/1383411/how-to-create-copy-button

Can't do that as is. And no way we put flash in navitia-playground ;)

**Comment by TeXitoi** [comment]
maybe a link?

**Comment by pbougue** [comment]
yep, could be nice.

**Comment by TeXitoi** [comment]
Do we put the token in the link?

**Comment by pbougue** [comment]
nope, the goal when I asked it was to allow people to share their navitia query avoiding to share their token (and if they want the token, there is still the url even though it includes playground)
