### ISSUE TITLE
Duplicate on google chrome changes the filled fields

### ISSUE THREAD

**Issue by WilliamFoster** [CanalTP/navitia-playground#153]
When doing a duplicate on google chrome the field token api and path element are changed when it should stay the same. 
![bug](https://cloud.githubusercontent.com/assets/13660730/17017139/6ee51d16-4f32-11e6-8c1a-66c27fb28418.png)

**Comment by TeXitoi** [comment]
I have no idea. I've seen it on android when reopening a dated tab. If anyone have an idea...

Workaround: reload page.
