### ISSUE TITLE
Amélioration design mineurs

### ISSUE THREAD

**Issue by colinele** [CanalTP/navitia-playground#165]
- [ ] Changer le visuel de la home (navitia superhero) j’ai déjà fait le visuel (voir avec Stéphanie pour le fichier)
- [ ] Revoir le rose (prendre un qui jure moins, ou le remplacer par du violet) ;
- [ ] Mettre une marge gauche plus large pour les listes déroulantes ;
- [ ] Ajustement de couleur pour le « ADD » quand il n’est pas dans un label bleu ;
- [ ] Affiner les traits de couleurs des labels ;

pour plus de précisions voir stéphanie

**Comment by TeXitoi** [comment]
J'ai du légèrement retouché le bleu foncé qu'on retrouve sur le bouton GO et sur les liens.

J'ai aussi un peu éclairci le liens en surbrillance.

**Comment by antoine-de** [comment]
super image !
