### ISSUE TITLE
Support upload file functionnality

### ISSUE THREAD

**Issue by TeXitoi** [CanalTP/navitia-playground#166]
The idea is to upload a json file to visualize. We need to know how to propose the functionnality.

**Comment by pbougue** [comment]
Konami code!

**Comment by pbougue** [comment]
Or a file drop in url ?

**Comment by TeXitoi** [comment]
A first and simple version is to just add a link in the homepage and make a dedicated page. Then, an improvement is to add it to the "menu" in the header.

**Comment by pbougue** [comment]
Yep, next to the "url" part
