### ISSUE TITLE
Trim token

### ISSUE THREAD

**Issue by l-vincent-l** [CanalTP/navitia-playground#184]
When you copy and paste token from navitia.io website spaces are added at the beginning.
Fixing navitia.io would be great, trimming spaces at the beginning and the end of apikeys too.

**Comment by TeXitoi** [comment]
I'm not found of modifying the data given as it makes some possibly credible request impossible. Maybe that's not really a problem in the case of a token.

What do you think?

**Comment by l-vincent-l** [comment]
I think that each time I try to copy/paste my token from navitia.io I have to remember to delete the spaces at the beginning, and that's not very pleasant.

**Comment by TeXitoi** [comment]
Technically, no, we are not always producing the token: anyone can create an instance of navitia, and then any token can be created. But that's true that I can't imagine why someone will do that ;-)

**Comment by xlqian** [comment]
I think it's reasonable to delegate this problem to navitia.io: stripping the space when copying the token
