### ISSUE TITLE
Addition of Landing & Boarding Pictograms

### ISSUE THREAD

**Issue by ludogithub** [CanalTP/navitia-playground#215]
Hi,

Maybe we can add new pictograms for boarding and landing following the integration of new datasets in Canada British Columbia:

![image](https://cloud.githubusercontent.com/assets/9010428/19808312/99172120-9d24-11e6-87c3-520d3f7a3973.png)

Many thanks,

Ludo Data Team

**Comment by TeXitoi** [comment]
These physical modes are not used: https://api.navitia.io/v1/coverage/ca-bc/physical_modes/physical_mode%3ACheckIn/vehicle_journeys

I don't have any picto for them. I can add them easily if I have them. Shuttle is also laking.
