### ISSUE TITLE
Bower Issue Running gulp

### ISSUE THREAD

**Issue by nikiizvorski** [CanalTP/navitia-playground#292]
Hi i have this issue happening when i try to run it with gulp.

Error in plugin 'run-sequence(dev)'
Message:
    The bower package jquery has no bower configuration file.

**Comment by TeXitoi** [comment]
Did you `sudo npm install gulp -g && sudo npm install bower -g && npm install && bower install`, especially the bower commands?

**Comment by nikiizvorski** [comment]
Yes issue is resolved and completely fine! Thanks you
