### ISSUE TITLE
"from" autocomplete returns "[object HTMLSpanElement]"

### ISSUE THREAD

**Issue by prhod** [CanalTP/navitia-playground#293]
Steps to reproduce : 
From this URL : http://canaltp.github.io/navitia-playground/play.html?request=https%3A%2F%2Fapi.navitia.io%2Fv1%2Fcoverage%2Fit%2Fjourneys%3F

Add a "from" parameter, type `Calle Fenice` and select `Calle de la Fenice (Venezia)`
=> the `from` parameter contains `[object HTMLSpanElement]`

**Comment by TeXitoi** [comment]
That's a navitia bug: https://api.navitia.io/v1/coverage/it/places?q=Calle%20Fenice& have `id: ""`

**Comment by prhod** [comment]
ok, thanks
