### ISSUE TITLE
De-corellation between the path and the "high level" service

### ISSUE THREAD

**Issue by stifoon** [CanalTP/navitia-playground#54]
I think it would be more explicative to seperate the path and the optional service.
For example, you can request a stop_schedule on coords, on a stop_area, on an entire line... and it's not really visible. And you could systematize the binomial "object_type/object_id" in the "build your path" section

![apihm](https://cloud.githubusercontent.com/assets/2752490/15705408/8c2c638a-27ef-11e6-8dc8-3c1e77331f8b.png)

What do you think? (note the beautiful font in the picture :) )

**Comment by TeXitoi** [comment]
@stifoon is it OK now with the new color for the feature ? If it is please close this issue.
